### ISSUE TITLE
Scrum Master

### ISSUE THREAD

**Issue by pfd1004** [dmh1006/Practica-2-Scrum-Master#30]

**Comment by vpp1004** [comment]
Es quien garantiza que el marco scrum funcione, moderando las reuniones de scrum
diarias y gestionando la resolución de impedimentos identificados en éstas, para
mantener el avance del equipo.
Agrupar la responsabilidad del funcionamiento de scrum en el rol de scrum
master resulta aconsejable cuando el product owner o el equipo tienen poca
experiencia utilizando scrum, o en organizaciones grandes, con un flujo continuo de
rotación o formación de personal. En equipos pequeños, estables y con niveles de
agilidad consolidados, las responsabilidades de funcionamiento y mejora del marco
de scrum pueden estar ya interiorizadas y asumidas por el equipo en conjunto.
